name: Build LaTeX document
on: [push]
#on:
 # push:
  #  paths: sample.tex
#    branches-ignore:
#      - '**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: sample.tex
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: sample
          path: ./sample.tex
